name: CI

on:
  pull_request:
    paths:
      - tf/**
      - .github/workflows/**
  push:
    branches:
      - main
    paths:
      - tf/**
      - .github/workflows/**

permissions:
  contents: read

jobs:
  validate:
    uses: glitchedmob/infra-gha/.github/workflows/tf-validate.yml@v0.2.0
    with:
      working-directory: tf
      init-backend: false
